In [1]:
import numpy as np

Rotation and transformation matrices

In [4]:
def R_x (theta): 
    R_x = np.array([[1,0,0], [0,np.cos(theta), -np.sin(theta)], [0,np.sin(theta), np.cos(theta)]])
    return R_x

def R_y (theta):
    R_y = np.array([[np.cos(theta), 0, np.sin(theta)], [0,1,0], [-np.sin(theta), 0, np.cos(theta)]])
    return R_y

def R_z (theta):
    R_z = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta),0], [0,0,1]])
    return R_z

def end_effector(x,y,z):
    p = np.array([x,y,z,1])
    return p 

def H_trnsf(R,p):
    H = np.array([[R[0][0], R[0][1], R[0][2], p[0]],
            [R[1][0], R[1][1], R[1][2], p[1]],
            [R[2][0], R[2][1], R[2][2], p[2]],
            [0,0,0,1]])
    return H

- SCARA 

In [9]:
def SCARA(q1,q2,h1,h2,l1,l2):
    H01 = H_trnsf(R_z(np.deg2rad(q1)),end_effector(0,0,h1))
    H12 = H_trnsf(R_z(np.deg2rad(q2)),end_effector(l1,0,0))
    H23 = H_trnsf(R_y(np.deg2rad(90)),end_effector(l2,0,0))
    p = end_effector(h2, 0, 0)

    return H01@H12@H23@p

In [11]:
SCARA(30,45,10,3,15,20)

array([18.16676196, 26.81851653,  7.        ,  1.        ])

- Stanford

In [15]:
def Stanford(q1,q2,h1,l1,l2):
    H01 = H_trnsf(R_z(np.deg2rad(q1)),end_effector(0,0,0))
    H12 = H_trnsf(R_x(np.deg2rad(90)),end_effector(0,0,h1))
    H23 = H_trnsf(R_y(np.deg2rad(q2)),end_effector(0,0,0))
    H34 = H_trnsf((np.eye(3)),end_effector(0,0,l1))
    p = end_effector(l2, 0, 0)

    return H01@H12@H23@H34@p

In [16]:
Stanford(30,45,10,5,15)

array([ 8.71191481, 13.19479217, 10.        ,  1.        ])

- Drone

In [20]:
def Drone():
    H01 = H_trnsf(np.eye(3),end_effector(0,0,10))
    H12 = H_trnsf(R_x(np.deg2rad(30)),end_effector(0,0,0))
    H23 = H_trnsf(R_z(np.deg2rad(60)),end_effector(0,0,0))
    p = end_effector(0, 0, 3)

    return H01@H12@H23@p

In [21]:
Drone()

array([ 0.        , -1.5       , 12.59807621,  1.        ])